apiVersion: xl/v1
kind: Blueprint
metadata:
  projectName: Extended Jenkins Ansible Pipeline
  description: |
    This is a simple release tempalte that uses Ansible and Jenkins.
  author: XebiaLabs
  version: 1.0
parameters:
  - name: FolderName
    type: Input
    description: What is the Folder name?
  - name: AppName
    type: Input
    description: What is the Application name?
  - name: ANSIBLE_HOSTNAME
    type: Input
    description: What is the Ansible Host name?
  - name: ANSIBLE_PORT
    type: Input
    description: What is the Ansible Server Port?
  - name: ANSIBLE_USERNAME
    type: Input
    description: What is the Ansible Host username?
  - name: ANSIBLE_PASSWORD
    type: Input
    description: What is the Ansible Host password?
  - name: JENKINS_URL
    type: Input
    description: What is the Jenkins URL?
  - name: JENKINS_USERNAME
    type: Input
    description: What is the Jenkins username?
  - name: JENKINS_PASSWORD
    type: Input
    description: What is the Jenkins password?
  - name: DB_USERNAME
    type: Input
    description: What is the DB username?
  - name: DB_PASSWORD
    type: Input
    description: What is the DB password?

files:
- path: xebialabs/xld-environment.yaml.tmpl
- path: xebialabs/xld-infra.yaml.tmpl
- path: xebialabs/xld-application.yaml.tmpl
- path: xebialabs/xlr-configuration.yaml.tmpl
- path: xebialabs/xlr-pipeline.yaml.tmpl
- path: xebialabs.yaml
